elastio/elastio-snap

- .drone.yml
- repobuild/deb/gen-repo.conf
- repobuild/deb/gen-repo.sh
- Added Drone pipeline to build assurio-snap packages 
- Added steps to the Drone pipeline and scripts to build and sign packages repository.
> packages repo for Debian8+/Ubuntu 16.04+

- .drone.yml
- BUILDING-PACKAGE.md
- app/aioctl.c
- dist/assurio-snap-dkms-conf
- dist/assurio-snap.spec
- src/Makefile
- src/assurio-snap.c
- src/assurio-snap.h
There are improvements for Fedora build, fix for kernel 5.4 etc.
> Upadte from upstream

- .github/workflows/ci.yml
Also added more logging for the repo build trigger
> Fix source branch transmission through json curl's arg

- .github/buildbox/Vagrantfile
- src/elastio-snap.c
> Fix memory leak on free of cloned bio

- .github/buildbox/Vagrantfile
- .github/workflows/ci.yml
- src/elastio-snap.c
> Fix submit_bio for cloned bio

- .github/buildbox/Vagrantfile
- src/elastio-snap.c
> Avoid system crash during memory overflow

- src/elastio-snap.c
- tests/test_setup.py
> Allow COW file to be located on non-protected volume

- src/elastio-snap.c
> Allow snap device to be readable after memory overflow is happen

- .github/workflows/ci.yml
It was agreed to add `lsmod` output to ease the detection of problems related to the module reference counter
> Show additional debug information

- .github/workflows/ci.yml
- app/bash_completion.d/elioctl
- app/elioctl.c
- doc/elioctl.8
- doc/elioctl.8.html
- doc/elioctl.8.md
Share all IOCTL API on elioctl
> Share all api to elioctl

- app/elioctl.c
- src/elastio-snap.c
- src/elastio-snap.h
- tests/elastio_snap.py
- tests/test_destroy.py
- tests/test_setup.py
- tests/test_storage_redirected.py
- tests/test_transition_incremental.py
There is for https://github.com/elastio/elastio-snap/issues/197
> Tests and behavour for redirected cow file

- .github/buildbox/Vagrantfile
- .github/workflows/ci.yml
Closes elastio/blue-stack#6156.
Closes https://github.com/elastio/infraworld/issues/345.
> [Internal/CI] Use OIDC role-based auth for aws operations

- lib/libelastio-snap.c
- src/configure-tests/symbol-tests
- src/elastio-snap.c
- src/elastio-snap.h
- src/includes.h
This is an interim PR into the `develop` branch to make sure the progress on this epic is tracked. Some tests are not working (which is OK) and the feature works not all kernels. There will be additional tasks for that in this epic.
Closes #220 
Closes #221
Closes #224 
Closes #225
> [Draft] Implement direct read/write IO

- .github/workflows/ci.yml
- src/elastio-snap.c
* Added default behavior if the orig_mrf is not found
* Minor fix for the direct IO functionality (return error code)
Closes #237
> Add default bio path if orig mrf is not found

- dist/elastio-snap.spec
> Bump the new version v0.12.2

- .github/workflows/ci.yml
- tests/devicetestcase.py
- tests/test_update_image.py
- tests/util.py
Added python test for multiple update-img usage and some basic data integrity check
Closes #254
> Implement test for fsck on the resulting incremental after multiple snapshots

- .github/buildbox/Vagrantfile
- .github/workflows/ci.yml
- dist/elastio-snap.spec
- Added Debian12 in CI build matrix
- Added Debian12 to available vagrant boxes list
- Removed obsolete box version constrains in Vagrantfile
Closes #273
> Add build for Debian12

- .github/workflows/ci.yml
- Increased AWS token expiration timeout
Closes #283
> [CI] Increase AWS token expiration timeout

- .github/workflows/ci.yml
- tests/util.py
Seemed to be a timeout issue. Increased timeouts for the CI tests.
Closes #285
> Driver can't insmod on ext3 on rare occasions

- .github/workflows/ci.yml
Related to elastio/elastio#8012
> Replace ASSURIODEV_OIDC_AWS_ROLE_ARN secret with aws_assuriodev_role_arn var
