elastio/elastio-snap

.drone.yml

The packages for a commit for some particular branch are already uploaded to the `...${DRONE_BRANCH}/deb` after a commit was pushed to a branch and before PR has been created. And no need to make upload one more time from a PR.

Avoid deb packages upload from the pull requests

---

.drone.yml
repobuild/rpm/gen-repo.sh
repobuild/rpm/rpm-sign.exp

1) Fixed build conditions in the yaml script to avoid packages upload
in the PR builds.
Tabulation in the .drone.yml was wrong. "when" word was related to
the build step settings, but not to the build step.
2) Added error handling to the rpm repo build script.
3) Added mirror files for CentOS 6, 7, 8 since CentOS 6 packages
installabe on the newer CentOS versions.

Multiple improvements for the CentOS repository build

---

.drone.yml
repobuild/collect_artifacts.sh

- repobuild/collect_artifacts.sh is more universal now. It can collect
artifacts of the different Debian, Fedora, Amazon Linux versions.
- Fixed a mistake when detecting distro ver.
Resolves #9

Add builds for Fedora 31, Amazon Linux 2, Debian 9, 10

---

src/configure-tests/feature-tests/Makefile

There was a message like 'find: .../build/configure-tests/feature-tests/build/ No such file or directory'
During the dkms build of the kernel module sources.
As it turned out, this doesn't affect feature tests build and execution. Because it's happens just on the 'clean' target when is nothing to clean. It's an installation of the kernel module package or first clean dkms build. But anyway it's fixed.
Resolves #13

Fix an error message during kernel module installation

---

dist/assurio-snap.spec

DKMS has dependency on the kernel-devel, but unfortunately kernel-debug-devel is installed instead on Fedora/CentOS.
Changed OrderWithRequires statement to the Requires to ensure kernel-devel is installed.
See more here https://github.com/assuriosw/assurio-snap/issues/12 and here https://bugzilla.redhat.com/1228897
This change ensures installation of the kernel-devel, not kernel-debug-devel if both dkms and kernel module are installed in one transaction. The installation order is preserved.
Left as it is for SLES.
Resolves https://github.com/assuriosw/assurio-snap/issues/12 in case if machine runs with the most recent kernel.

Fix kernel-devel dependency instalation with the kernel module

---

.drone.yml
repobuild/upload.sh

Now each build is separate pipeline due to exec runner limitations.
Added upload script which is used instead of the drone s3 plugin.
Drone "downstream" plugin is still used to trigger packaging build.

Use drone exec runners for the packages build

---

.drone.yml

This label is used to distinguish VMs on the build server between build and test ones.

Add "kind" label of the build runners

---

README.md

Fix accidental replacement of Datto -> Assurio in README.md

---

src/elastio-snap.c

Fixed possible memory leak in a case when
'buff_dev_name' is NULL and 'buff_dir_name' hold a memory
or when 'buff_dir_name' is NULL and 'buff_dev_name' hold a memory.

Fix of memory leak

---

.github/vagrantfiles/amazon2-amd64-build/Vagrantfile
.github/vagrantfiles/centos6-amd64-build/Vagrantfile
.github/vagrantfiles/centos7-amd64-build/Vagrantfile
.github/vagrantfiles/centos8-amd64-build/Vagrantfile
.github/vagrantfiles/debian10-amd64-build/Vagrantfile
.github/vagrantfiles/debian8-amd64-build/Vagrantfile
.github/vagrantfiles/debian9-amd64-build/Vagrantfile
.github/vagrantfiles/fedora31-amd64-build/Vagrantfile
.github/vagrantfiles/fedora32-amd64-build/Vagrantfile
.github/workflows/ci.yml
.gitignore

1) Updated ci.yml to use Vagrant boxes for the driver and packages
build.
2) Added 'start a box', 'destroy a box' build steps.
3) Copied Vagrant files from the packaging and removed all GPG related
stuff from them.
4) The jobs 'Artifacts manifest' and 'Trigger repo upload' are running
directly on the baremetal runners. They need just curl and aws cli
and I don't see any reason to "pack" these simple operations into the
Vagrant boxes. Also they are distribution independent.
Closes #35

Add Vagrantfiles for CI

---

.github/buildbox/Vagrantfile

Now we have own workaround with usage of the Vagrant::Action::Builtin::BoxAdd triggers
The workaround is for the problem, when 2 parallel "vagrant up"s add or update a box.
Vagrant is using the same temporary file for download for both parallel downloads.
As result, file was corrupted and both or at list one "vagrant up" was failing.
NOTE: The version number is not strict. It's equal or hier than the defined
value. That's because, mainly, boxes are updated for elastio builds, not
elastio-snap builds. That's why the box version will be updated in this
repo less frequently than the new boxes will appear.

Use versioned Vagrant boxes for CI

---

.github/workflows/ci.yml

'if: always()' is added to prevent cancellation of the
'vagrant up' build step. Otherwise, if a build ic cancelled during the
'vagrant up', then 'vagrant destroy' is failing with the long error
messege like here:
https://github.com/elastio/elastio/runs/1110832997?check_suite_focus=true#step:8:55

Prevent cancellation of the 'vagrant up' build step

---

src/configure-tests/feature-tests/proc_create_fn_file_operations.c
src/configure-tests/feature-tests/proc_create_fn_proc_ops.c
src/elastio-snap.c

- Used structure of the proc_ops type as argument for the proc_create
function. The prototype of this function is changed since kernel 5.6.
- Updated existing feature test to check argument type for the
file_operations structure and added new test for the same function and
another argument of type proc_ops.
This fix resolves #24 about driver build failure on Fedora 31 with the kernel v. 5.6. However Fedora 31 now has kernel v. 5.8.
I'm going to crate another issue for it.

Fix driver build on the Linux kernel v. 5.6

---

INSTALL.md
README.md

Correct snapshot device name in the README.md
- Changed snapshot device name from the  /dev/elastio[N] to the the /dev/elastio-snap[N].
- Highlighted commands as code to make README.md better readable.
Fix typo in the installation instruction for Amazon Linux 2 in the INSTALL.md
- There was an extra % in the link to the Amazon 2 repo package.

Correct some inaccuracies in README.md and INSTALL.md

---

.github/buildbox/Vagrantfile
.github/scripts/check_env.sh
.github/scripts/destroy_box.sh
.github/scripts/detect_branch.sh
.github/scripts/dispatch_packaging.sh
.github/scripts/set_env.sh
.github/scripts/start_box.sh
.github/workflows/ci.yml

It became not a one line, that's desided to extract it to a script and
call it where it's necessary in different jobs.
Than decided to remove all bash-like GHA scripts to separate files from
the ci.yml
Also fixed wrong export of some branch names to a Vagrant box.
Resolves #45

Fix detectin of the source branch

---

.github/scripts/detect_branch.sh
.github/scripts/dispatch_packaging.sh
.github/scripts/set_env.sh
.github/workflows/ci.yml

The new failures are appeared after the previous fix.
This time upload script gets a wrong argument (target path, witch contains
branch name).
Example: https://github.com/elastio/elastio-snap/runs/1180619657
That was just because checkout sources at the beginning of each job was
forgotten. It completely explains wrong behaviour, described in the
https://github.com/elastio/elastio-snap/issues/45
Finally resolves #45

Fix "floating" bug with undefined source branch on CI

---

.github/workflows/ci.yml
tests/elio-test.sh

No need to upload packages in case if module is not installable.
The appropriate step has been added to the build. It makes and installs
the kernel module.
Then it runs Python tests.
Closes #30

Add module build and tests to the build steps on CI

---

tests/devicetestcase.py
tests/test_destroy.py
tests/test_setup.py
tests/test_snapshot.py
tests/test_transition_incremental.py
tests/util.py

Now tests are use first available loop device.
Also added random number to the hardcoded file name for the loop device
and mountpoint. Maybe some time later some tests will run in
simultaneously.
And minor is in the available range of 0..23.
Closes #52

Get rid of hardcoded 'loop0' device in tests

---

.github/scripts/set_env.sh

It's replaced in accordance to the new approach how to set build env vars, described here
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
Closes https://github.com/elastio/packaging/issues/31

Remove deprecated set-env from ci.yml

---

INSTALL.md

It would be great if it could be possible to add dependency of the 
kernel-devel-CURRENT_KERNEL_VER to dkms-elastio-snap package.
Unfortunately there is no solution how to add a variable to the 'Requires: package = version_var'
and detect it during the installation. The version have to be a constant.
Hence just updating INSTALL.md with instantiation to install `kernel-devel-$(uname -r) ` if running
not a fresh kernel.
Closes #55

Add info to INSTALL.md about kernel-devel dependency

---

src/configure-tests/feature-tests/freeze_super.c
src/elastio-snap.c

freeze_super do much more work comparetively with the freeze_bdev. It
syncs filesystem and waits for pending writes.
In case of XFS v5 freeze_bdev doesn't freeze super.
Used freeze_super instead of freeze_bdev for any fs and all kernels,
where this function is present.
Fixes #59

Fix fs corrupt on XFS v5

---

.github/workflows/ci.yml
dist/elastio-snap.spec
src/elastio-snap.c
src/elastio-snap.h
tests/elio-test.sh

There are fixes for:
- kernel 4.9 and SCSI driver conflict.
Interesting facts about this fix (7ea4ee4):
- It also fixes problem of the kernel module usage with the loop devices on Debian 9 (kernel 4.9.0-13) and resolves issue #50.  
- This fix has been reverted in upstream https://github.com/datto/dattobd/commit/275ac8bbce578a09d23961bbd675a7c05176a5b6
- ~multipage bio requests~
I was intended to merge it too, but this commit https://github.com/datto/dattobd/commit/9a15da2c9216b861a635101071e7a08e07af20bf breaks tests https://github.com/elastio/elastio-snap/runs/1444115356
Also it was reverted in upstream https://github.com/datto/dattobd/commit/bb24cbca415e23abad9a2776a243930ad2ee2594
So, finally it's removed from this PR.
- package build with new RPM version (18a62c4 and 5fa6d6e).
Also …

Update from upstream

---

src/elastio-snap.c

There was a fix for the 4.9 kernel and Debian 9 0035e38
It's great and in addition somehow fixes a problem of the driver and
loop devices. It relies on the 'req_op' structure presence, which
appeared in the kernel 4.9 and replaced with the 'req_opf' in the next
kernel versions.
CentOS 7 has enum req_op starting from the version 7.4, kernel
3.10.0-693, because they are doing backports from the 4th kernels.
But this enum has just 4 values instead of 6 as in other kernels,
where this enum is present. And it doesn't have defined REQ_OP_BITS,
which could could be defined and equal to the 2 bits.
As a fix, the condition is changed when to use passthrough 28 (kernel
4.9) instead of 30 (other kernels and CentOS's kernel 3.10).
Resolves #64

Fix incremental snapshots on CentOS 7.4+

---

dist/elastio-snap.spec

There were few problems with the kernel module package uninstall.
Interesting, but it was reproduced just with the deb packages.
So, uninstall was unsuccessful in these cases:
- `lsmod | grep elastio-snap` returns nothing. The loaded module name is
always with the replaced hyphen with underscore. Now we are greping an
appropriate string.
- in case if `elastio_snap` kernel module was already unloaded by
`rmmod` command.
- in case if `elastio-snap` kernel module files were alredy removed by
`dkms`.
Resolves #66

Fix '%preun' action for the kenel module package

---

dist/elastio-snap.spec

Interestingly, CentOS 7, Ubuntu 20.04 have the same DKMS 2.8 version.
Debian 10 has older DKMS 2.6.
DKMS from CentOS restarts systemd-modules-load service
after module installation and depmod operation. DKMS from
Debian/Ubuntu doesn't.
And the 'POST_INSTALL' in the dkms.conf to run a script using
`modprobe` doesn't help either, because it's called after installing
the module, but before calling `depmod`.
Thus, the only way to load the module after installation is to
explicitely call `modprobe` on the `%post`-install action.
Resolves #68

Load module after install on Debian/Ubuntu

---

.github/scripts/set_env.sh
.github/workflows/ci.yml
src/elastio-snap.c
tests/devicetestcase.py
tests/elio-test.sh

- **Linux kernel 5.8 support**
A block device requests queue has a function 'make_request_fn' which is
used in the driver to send requests to the device underlyng to a
snapshot. Suddenly, starting from the kernel 5.8, this function has
become empty (NULL) in most cases.
Used call of the similar function 'blk_mq_make_request' in case if the
'make_request_fn' is not set. This call is wrapped into the
elastio_snap_null_mrf function with the memory barrier before call
blk_mq_make_request. Otherwise driver hangs on the snapshot destry
operation.
Resolves #44
Note: build of the driver on the Linux kernel 5.8 has been already fixed
in the #48, commit 96d63d.
- **Added possibility to use real block device in tests and enabled build and tests for Fedora 31**
Now name of the device can be specified …

Linux kernel 5.8 support

---

.github/workflows/ci.yml
src/elastio-snap.c
tests/devicetestcase.py

**Fix, part 1**
There was a failure like this:
`percpu ref (blk_queue_usage_counter_release) <= 0 (-149) after switching to atomic`
at the moment when test was trying to destroy a loop dev.
The queue's usage counter was not incremented each time when blk_mq_make_request
has been called. Fixed it by the manual increment, so it have to be >= 0 before
it's destroyed.
Interesting nuance that the issue is observed just on the loop devices,
but it seems to be not a loop dev specific.
**Fix, part 2**
elastio_snap_null_mrf function was mistakenly set to the original device after a
snapshot has been destroyed and tracking has been finished. Now it's set
back to the NULL.
Updated tests:
- Removed a "special case" in the tests for Fedora 31 with the Linux 5.8.
Now each distro has 2 steps with the …

Fix tests on the loop dev on Linux 5.8

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml
src/configure-tests/feature-tests/bdops_submit_bio.c
src/configure-tests/feature-tests/blk_mq_submit_bio.c
src/configure-tests/feature-tests/make_request_fn_in_queue.c
src/configure-tests/feature-tests/thaw_bdev_int.c
src/configure-tests/symbol-tests
src/elastio-snap.c

2 main problems are solved:
1. make_request_fn function in the queue has been replaced with the
submit_bio function in the const struct block_device_operations.
Now it's still replaced with the tracing_mrf with usage of the trick
with disabling the memory read-only access protection during this
operation.
2. This submit_bio function can be not set (NULL), as it was with the
make_request_fn in the kernel 5.8. And the blk_mq_submit_bio (ex.
blk_mq_make_request) helps again in this case. But it became not
exported since 5.9.2. As result, it's called by the memory address
So, the fix is a bit fragile and hacky, but it resolves a problem of the
separate queue of the stolen bios and delays significant change in
the architecture of this driver.
Minor fixes for the kernel 5.9 support:
- Fixed …

Support Linux kernel 5.9 and 5.10

---

INSTALL.md

The repo package has been moved from the x86_64 to the noatch directory.
The INSTALL.md has been changed accordingly.

Fix repo package installation instructions

---

.github/workflows/ci.yml

Unblocking our CI with the temporary workaround until #78 is not fixed.

Apply workaround for the CentOS 8 driver hang issue

---

src/elastio-snap.c

After the snap setup we got to wait for interruptible timeout
till (busy state) atomic lock would be released.
Closes #26

Wait for snap release after IOCTL_SETUP_SNAP handling

---

src/configure-tests/feature-tests/blk_mq_make_request.c
src/elastio-snap.c

- Fixed blk_mq_make_request feature test;
- Fixed work with the the loopback devices;
- Used new compat HAVE_BLK_MQ_MAKE_REQUEST instead of the
HAVE_BLK_ALLOC_QUEUE_MK_REQ_FN_NODE_ID where it's applicable;
- Simlified `find_orig_mrf` function, reordered defines and
reduced code duplication.
My comments in the https://github.com/elastio/elastio-snap/pull/85 have been addressed here.

Apply fixes per code review comments

---

.github/workflows/ci.yml
src/configure-tests/feature-tests/blk_mq_make_request.c
src/elastio-snap.c
src/includes.h

Closes #78 
CentOS 8 kernel 4.18.0-305 does contain some new stuff from 5.x newer
kernels. Also, on this kernel it's possible to have default MRF==NULL at
snap creation stage.
So in this case we have to create default MRF by blk_mq_make_request
kernel API function which is one of those new ones imported by
CentOS 8 from the newer kernels.
Added compat for blk_mq_make_request.

Support CentOS 8 kernel 4.18.0-305 when MRF is NULL at snap creation

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml
src/configure-tests/feature-tests/blk_mq_submit_bio.c
src/elastio-snap.c
src/genconfig.sh

- Fix blk_mq_submit_bio compat.
- Fix build script for asm-linkage on Debian-11 by using it's specific
map file.
- Use blk_mq_submit_bio as asm-linkable for all 5.9+ kernels.
Also handled specific Debian 11 only case with the empty but existing
/boot/System.map-kernel_ver file.
See https://www.mail-archive.com/debian-devel@lists.debian.org/msg369037.html
Used 2 workarounds:
1) Try /usr/lib/debug/boot/System.map-kern_ver location if package
linux-image-$(uname -r)-dbg is installed.
2) Unfortunately option 1 isn't a case when the new kernel version is just
installed and DKMS is used to build our module. Using /proc/kallsyms
in this case is Ok, because relative function addresses has been used in the
code.
Closes #83

Fix stuck on Debian 11

---

.github/scripts/dispatch_packaging.sh

Now we have to specify source and target branches.
For the elastio-snap they are always equal.
The change is just to honor new format.
Related to https://github.com/elastio/packaging/issues/128

Trigger repo build with the new payload

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml
src/configure-tests/feature-tests/bio_bi_bdev_bd_disk.c
src/configure-tests/feature-tests/bio_copy_dev.c
src/configure-tests/feature-tests/bio_set_dev.c
src/configure-tests/feature-tests/notify_change_3.c
src/configure-tests/feature-tests/task_struct_state.c
src/configure-tests/feature-tests/vfs_unlink_3.c
src/configure-tests/symbol-tests
src/elastio-snap.c

Calling original mrf for cloned read bio request did fix the corrupts
on 5.12+, but certainly we need to use it for all kernels, as it looked
like a big defect in driver that could sooner or later have surfaced.
- Added Fedora 33 and 34 to CI.
- Fixed HAVE_BIO_BI_BDEV check.
- Added compats for 5.13:
bio_bi_bdev_bd_disk, notify_change_3, vfs_unlink_3
Also, there minor changes to have more accurate kernel functions calls:
- Removed freeze/thaw super, using only freeze/thaw bdev.
- Prettified the conditions for orig_mrf usage in tracing_mrf.
- Added compats for bio_copy_dev and bio_set_dev.
- Use get_super and drop_super asm-linkable ones for superblock access.
Closes #84

Fix the submitting of cloned read bio request

---

.github/workflows/ci.yml
src/configure-tests/feature-tests/alloc_disk.c
src/configure-tests/feature-tests/disk_live.c
src/configure-tests/feature-tests/locks_verify_truncate.c
src/configure-tests/symbol-tests
src/elastio-snap.c

- Added compats for the removed functions `locks_verify_truncate` and
`alloc_disk`.
- Added compat for the added function `disk_live`.
- Replaced anchor address of the `printk` function with the address of
the `kfree` function. `printk` still exists in the kernel 5.15, but
it's a macros around `_printk`. So, `printk` doesn't have an address
in the `System.map` or `/proc/kallsyms` files.
- Removed redundant `elastio_snap_drop_super` function and simplified
logic around `elastio_snap_get_super`. The last one is necessary,
because `get_super` function is not exported since 5.11.

Linux kernel 5.15 support

---

dist/elastio-snap-dkms-conf
dist/elastio-snap.spec

= Fix module loading after installation
It was broken by `dkms` update to version 2.8.8 on CentOS 7, 8 and all
supported Fedora versions. Now `dkms install` doesn't load a module
after installation without parameter `--modprobe-on-install`. And used
script `/usr/lib/dkms/common.postinst` still don't pass this parameter
to the `kms install -m $NAME -v $VERSION -k $KERNEL $ARCH` command.
The problem has been work-arounded by the manual modprobing of the
module at the end of installation.
Closes #95
= Fix minor problem with installation logs noise
The log was spammed with the messages about deprecated `REMAKE_INITRD`
parameter.
`REMAKE_INITRD` was set to "no" which is the default value for DKMS
where this parameter was existing. And now starting from DKMS 3.0 it's
deprecated. Now it's just …

Fix module loading after installation

---

src/elastio-snap.c
tests/test_setup.py

This change helps to avoid hack with the replacement of the `const` member
function `submit_bio` in the `block_device_operations` structure.
So, now there is no need to disable/enable page protection when
tracing is started/stopped. Entire struct for the traced device is replaced now.
As experiment showed, this struct can be shared between multiple
devices. That was a root cause of the bug.
Also introduced new func `find_orig_fops` which is very like the
existing func `find_orig_mrf`. This is done to reduce count of
precompilation directives in the original function, which became
unreadable at all if still combined for kernels older and newer than 5.9.
Resolves #100

Fix ability to take snapshots from the multiple devices at one time on kernels 5.9+

---

INSTALL.md
src/configure-tests/feature-tests/si_mem_available.c
src/elastio-snap.c
src/genconfig.sh

- Fix module compilation due to absence of `si_mem_available` in some
kernels
This function is used to check available memory. However it has very
strange history. The function has been added in 3.16. But then it
disappears in the 3.17 and then appears back in the 4.4 and then it
disappears again in 4.5 and then appears back in 4.6.
Closes #116
- Fix warning during compilation on some 2.X, 3.X, 4.X kernels
Macros `READ_ONCE` produces warning during compilation on some old
kernels when it's used for `current->state`.
- Deny to `make` module w\o `sudo` when it can be done, but produces
a non-working kernel object file.

Fix module compilation on some 2.X, 3.X, 4.X kernels

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml
src/configure-tests/feature-tests/add_disk_int.c
src/configure-tests/feature-tests/bdops_submit_bio.c
src/configure-tests/feature-tests/bdops_submit_bio_uint.c
src/configure-tests/feature-tests/genhd_fl_no_part.c
src/elastio-snap.c

- Changed MRF function result type to VOID,
added helper macroses for that.
- Started from 5.15 blk_cleanup_queue should be called
right before put_disk.
Closes #106

Support kernel 5.16

---

Makefile
lib/Makefile

1. No generic way to locate the user library paths was found for all distros we support
2. Properly, this should have been solved with Autoconf, which we don't use at the moment
3. But as we produce deb/rpm packages, this should not be a problem for users. Still, for developers, there's a possibility to specify the installation prefix with `sudo make PREFIX=<prefix>`
5. Apart from that, there should always be a common path for the libraries: /usr/lib64
6. Hence, I've replaced the prefix to `/usr`, making the default installation path of `/usr/lib64`
7. Apart from that, added permissions check to make sure that driver is compiled with root rights so that kernel functions are located properly in `kernel-configs.h`

Change default library installation path and check permissions before build

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml
repobuild/collect_artifacts.sh
src/configure-tests/symbol-tests
src/elastio-snap.c
src/genconfig.sh
tests/test_destroy.py
tests/util.py

This PR **fixes** the issue with a syscall table location and provides **support for the `arm64` architecture**
From now on, elastio driver works on `x86` and `arm64` (`arm32` isn't supported so far)
Сloses #107
Сloses #120 
_Code changes:_
1. In latest kernels, `sys_mount` & `sys_umount` were changed to the architecture-dependent functions, f.e., `__x86_64_sys_mount` or `__arm64_sys_umount`.
2. These functions use `struct pt_regs * regs` as a parameter. Hence, `mount_hook` / `umount_hook()` functions have been refactored to work on different kernels
3. Macro `set_syscall` / `restore_syscall` have been rewritten to conform multi-architecture code structure. Underneath, it calls generic and arch functions to disable page protection, replaces the hook, and toggles the protection back: …

Fix syscall table location and add support of arm64 architecture

---

.github/workflows/ci.yml

This should help diagnose problems in or detected by tests like this #127
And changed display order of the distro name and arch in the builds output
from this
to this
First the name of the distribution, and then the architecture.

Show dmesg output after the tests

---

src/elastio-snap.c
tests/test_transition_incremental.py

Allow snap device to be readable after the cow file errors

---

.github/buildbox/Vagrantfile
README.md

The purpose of this update is to use new devboxes which will not
remove vagrant-libvirt network from the build servers.
Also fixed mistakes in the README.md regarding the snapshot device name.
Related to https://github.com/elastio/elastio/issues/5539

Update Vagrantfile to avoid deletion of the vagrant-libvirt network

---

src/elastio-snap.c
tests/test_destroy.py

This fix resolves the bug related to the dormant snapshot functionality:
- at the first mount, the block device is owned by the parent driver
- after the snapshot creation, we update ownership to the elastio driver
- because of this, v5.13+ kernels did additional module_put() for our module at umount
The behavior above is the reason for this fix.
To resolve this, when active and umount, we switch the ownership back to the parent, hence
making the umount independent from the perspective of the elastio driver. When the device
is mounted again, re-gain ownership over it.
Apart from it, we do this to prevent the kernel from freeing our block_device_operations installed (f.e, if the device is removed from the system)
Closes #134

Module refcnt becomes -1 on umount

---

.github/workflows/ci.yml

It's internal without changes in the driver.
Applied tag `elastio:dev=true` to the non-release and non-master builds
to make these artifacts expired later.
Related to https://github.com/elastio/ci/issues/155

add expiration tag for dev branches

---

.github/workflows/ci.yml
dist/elastio-snap.spec

- Updated ci.yml to download `linux-image-$(uname -r)-dbg`
- Updated `elastio-snap.spec` to add the abovementioned package as a dependency
See https://github.com/elastio/devboxes/pull/230 for more details
Closes #124

Enable Debian 11 tests on arm64

---

.github/workflows/ci.yml
src/configure-tests/feature-tests/bvec_iter_all.c
src/elastio-snap.c
tests/test_destroy.py
tests/test_transition_incremental.py
tests/util.py

The elastio driver was known to be unstable on the xfs filesystem, especially with LVM/RAID setups. Most of the problems are fixed with this commit.
The root cause lies in a plane of bio corruption caused by bio splitting which is done underneath without the driver being aware of it:
- elastio driver submits bio after `make_read_clone()`
- inside the system, LVM splits it into smaller bios, chaining them after the parent one
- elastio driver knows nothing about these chains
- `on_bio_read_complete()` we are notified about the blocks for parent bio only (please refer to `bio_split()`)
- hence, less information (pages, bytes) is received, but we are trying to operate with it as we have a full chunk of data
- this caused kernel corruption in different ways, which we observed in the following …

patch to fix [almost] all xfs problems

---

.github/workflows/ci.yml
INSTALL.md
dist/elastio-snap.spec
src/configure-tests/feature-tests/bio_alloc_bioset_5.c
src/elastio-snap.c
src/elastio-snap.h
src/includes.h

**Fixed 2 compilation errors on 5.18**
1. `genhd.h` has been removed and `gendisk` struct has been  moved to
the `blkdev.h` in the kernel 5.18. Used macros `__has_include` as an
easiest fix. Old compilers may not have this macros, but `genhd.h`
exists on those systems.
2. `bio_alloc_bioset` function now takes 5 arguments instead of 3.
Added compat for this function.
Closes #152 
**_Additional changes:_**
- **Added info about `aarch64` support into INSTALL.md**
Added "support platform matrix" into the same document and
added info about installation on Ubuntu 22.04.
- **Bumped new version**
The version has been increased from `0.10.17` to `0.11.0` due to
major changes in the driver, such as `aarch64` support, fixes for the
dormant snapshots functionality, LVM/raid support and recent …

Fix module compilation on Linux kernel 5.18

---

src/elastio-snap.c

Changed the order of functions to make `bdev_switch_ownership` end tracing before `handle_bdev_mount_nowrite`.
Resolves #147

Fix slab cache kernel warnings on rmmod

---

.github/workflows/ci.yml
src/elastio-snap.c

TL;DR
==
This is a reflection of fix 49826d1 recently made by @skypodolsky
for the LVM/RAID setups and driver stuck in the loop of the
`snap_handle_write_bio` function. This time the same fix is applied for
the read bios in the `snap_handle_read_bio` function.
Long description of the problem
==
An investigation was started from the hung of the `test_modify_origin`
unit-test on Debian 9 with Linux kernel 4.9 on volume `raid1` and `ext4`
file system.
The test contains the following steps:
1. setup snapshot of the raid volume
2. do some writes on the original volume
3. os.sync()
4. mount snapshot device
5. ...
The 4th operation led to a hang of the `mount` operation. Interesting
detail, the hang was not reproducible without `os.sync()` in the test or
on `xfs` fs (because `xfs` doesn't honour …

Fix driver stuck on ext4 raid1 volume on Debian 9

---

.github/workflows/ci.yml
tests/util.py

Fore some reason (probably for viy) we have to new manually installed
xfsprogs on the Debian 8 boxes. Fixed it by xfsprogs and libs
re-installation.
And adjusted work with `mdadm` utility in tests to work on old ( < 3.5)
Python.
No changes in the driver.
Resolves #139

Enable tests for XFS and raid/LVM on Debian 8

---

.github/workflows/ci.yml

The tests started to fail on Debian 8 due to a kernel panic after they were fixed here #160
It's a known bug in 3.16 kernel and `virtio` driver. 
It happens on mount of the raid1 device with XFS even if elastio-snap is not loaded.

Disable tests on RAID/xfs with qcow2 disks on Debian 8

---

src/configure-tests/feature-tests/bio_remapped.c
src/configure-tests/feature-tests/bio_throttled.c
src/elastio-snap.c
tests/devicetestcase_multipart.py

This fix closes #150 and _properly_ approaches the integration of the v5.16 Linux kernel.
Previously, during the integration of the v5.16 kernel, we had an issue with the partition mounting (`test_modify_origin` couldn't pass successfully). This issue was caused by the wrong sector offset calculation. Then it was [incorrectly] considered to be a new, changed approach to the sector calculation in the modern kernel. Now we see that understanding wasn't correct.
During debugging of issue #150, a similar behavior's been found on v5.15 (ubuntu 22.04, arm64). It was found that the issue is not related to the 5.16. Hence, the solution made during that time was rather a workaround and didn't actually explain the nature of the problem.
After proper debugging, it was seen that some bio requests …

Fixed attempt to access beyond end of device

---

.github/workflows/ci.yml
src/elastio-snap.c

Previously, in issue #134 we added the code dedicated to gaining and restoring the ownership over the block device. This has been implemented to make sure that the right entity (elastio_snap or parent driver) owns the device. As we have changed the ownership logic in the fix for #149, we can now revert this functionality and automatically fix this issue.
NOTE: please mind that this branch is on top of [this one](https://github.com/elastio/elastio-snap/tree/fix/149-xfs-lvm-randomly-fails). Only the last commit is what needs to be reviewed.

Removed code related to the bdev ownership change functionality

---

.github/workflows/ci.yml
src/elastio-snap.c

Briefly the case: a process called xfs_db (XFS debugging tool) obtained the original block device (`dm-4`) right before we switched the bdev fops (file operations). During this switch, we also change the ownership of our driver. This, in its turn, makes `xfs_db` execute `blkdev_put()` (with `module_put()` underneath) for `elastio_snap` (instead of the xfs driver), causing its refcnt to become -1. Here you may see the behavior (pay attention to the last line):
```
#
#
elioctl-1281    [007] .....   107.640097: blkdev_get_by_dev <-blkdev_get_by_path
elioctl-1281    [007] .....   107.640110: blkdev_put <-__ioctl_setup
elioctl-1281    [007] .....   107.640119: blkdev_get_by_dev <-blkdev_get_by_path
elioctl-1281    [007] .....   107.641435: __tracer_transition_tracing <-__tracer_setup_tracing …
```

refcnt becomes -1 at the snapshot creation on XFS

---

src/elastio-snap.c
tests/kmod.py

It was seen in #169 that in rare cases driver fails to unload on Ubuntu 22.04. This happens because, due to some reason unknown, the kernel increments the module refcount via the `owner` field. The issue was reproduced with CI tests only, there was no scenario found to reproduce it locally to debug deeper with additional tools.
In light of this, it was decided to comment the `owner` field, which doesn't seem to be causing additional stability issues on any distributive. Apart from that, additional retries were added to handle the module unloading process.
The fix has been deeply tested and proven itself as stable on all distros and architectures.
Closes #169

Driver fails to unload on Ubuntu 22.04

---

.github/workflows/ci.yml

It was seen that sometimes the timeout is not enough. Let's now set it to two minutes to see how it works.

Increased timeout in 'Show debug information' CI test

---

src/elastio-snap.c

It was seen that at the time when ioctl (transition to incremental) takes place, we still got some unprocessed bio in snap_cow_thread(). As the solution, it is proposed to add some wait in ioctl handlers to make sure all bio requests have been processed.
Here is the log explaining the behavior previously observed. Please take a look at the counters of the received (queued) and processed bio requests:
```
[  461.946031] elastio-snap: ioctl command received: 1074020613 
[  461.946033] elastio-snap: received transition inc ioctl - 19
[  461.946034] elastio-snap:    >> WAITING STARTED (bio received=61, bio processed=48)...
[  461.946759] elastio-snap: error handling write bio in kernel thread: -27
[  461.946034] elastio-snap:    >> WAITING FINISHED (bio received=61, bio processed=61)...
[ …
```

test_transition_fs_sync_cow_full fails on fedora 35

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml

- Added builds for CentOS Stream 9
- Updated checkout action from v2 to v3
- Allowed to run CI checks on event `pull_request_target`.
These checks will perform tests but will not upload artifacts.
This change allows to approve CI runs on PRs from external forks.
See doc for more info https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

Add builds for CentOS Stream 9 and allow CI runs on PRs from external forks

---

.github/workflows/ci.yml

- Changed `pull_request_target` to `pull_request`. The 1st one is too open
and don't require approval for CI runs from the forks.
- Filtered just some branches for CI runs on `push` to avoid too many CI
usage while pushing to a branch and creating a PR.
There are 3 allowed branch names: `master`, `release**`, and a special
one for "debugging on CI" `debug/**`.

Fix PR CI runs

---

src/elastio-snap.c

When cow file out of space, then snapshot switched to failed state. But this state not visible in elastio-snap-info. 
Steps to reproduce:
```
root# mkdir /tmp/fs
root# truncate -s 2G test.img
root# losetup /dev/loop16  test.img
root# mkfs.ext4 /dev/loop16
root# mount  /dev/loop16 /tmp/fs
root# elioctl setup-snapshot -c 10 -f 1 /dev/loop16 /tmp/fs/.eliosnap 0
root# dd if=/dev/urandom of=/tmp/fs/big_file count=100 bs=1M
root# dmesg | tail
[694212.900953] elastio-snap: cow file '/tmp/fs/.eliosnap' max size exceeded (4198400/1048576): -27
[694212.900960] elastio-snap: error writing cow data: -27
[694212.900963] elastio-snap: error writing cow data and mapping: -27
[694212.900965] elastio-snap: error handling write bio: -27
[694212.900967] elastio-snap: error handling write bio in kernel …
```

Show any errors on /proc/elastio-snap-info

---

src/configure-tests/feature-tests/bio_split_4.c
src/configure-tests/feature-tests/generic_make_request.c
src/elastio-snap.c

This PR closes the memory overflow issue on some cloud-based instances.
The root cause of memory overflow in #96 on the AWS EC2 instance was that we held the initial bio request [the one we want to backup] and all its "clones" for a significant amount of time. Briefly [more on that below!], this was possible due to several reasons:
- A big size of initial bio requests to backup (created by `cp` or `dd` - could be 10 MB or more)
- A small value of `/sys/block/<blockdevice>/queue/max_sectors_kb` that limits the size of a single bio request to be processed
- While processing the initial bio, this creates a bottleneck and forces the OS to additionally split bio requests which were cloned from the initial one
- Even more, the default scheduler [mq-deadline] reorders these cloned bio requests …

Split large bio requests in advance

---

src/configure-tests/symbol-tests
src/elastio-snap.c

Replaced `__alloc_disk_node()` with `blk_alloc_disk()` and reconsidered the relevant logic.
Closes #180

Revise disk allocation logic

---

src/elastio-snap.c

Steps for reproduce:
```
root@user-vm:/home/kgermanov# mount -l | grep sda
/dev/sda5 on / type ext4 (rw,relatime,errors=remount-ro)
root@user-vm:/home/kgermanov# mount -l | grep sdb
/dev/sdb1 on /home/kgermanov/work type ext4 (rw,relatime,errors=remount-ro)
root@user-vm:/home/kgermanov# elioctl setup-snapshot -c 10 -f 200 /dev/sda5 /home/kgermanov/work/.eliosnap/snap0 1
root@user-vm:/home/kgermanov# mount /dev/elastio-snap1 /tmp/fs -o ro
mount: /tmp/fs: cannot mount /dev/elastio-snap1 read-only.
root@user-vm:/home/kgermanov# dmesg | tail
[631779.274226] EXT4-fs (elastio-snap1): INFO: recovery required on readonly filesystem
[631779.274231] EXT4-fs (elastio-snap1): write access unavailable, cannot proceed (try mounting with noload)
[631779.274330] elastio-snap: mount returned: -30 …
```

When used redirected storage, it did not work.

---

.github/workflows/ci.yml

The new kernel 6 has been released and it's used on Fedora 37.
And Fedora 35 and 36 got updates with the new version.
However we do not support yet kernel 6 (#199) and Fedora 37 (elastio/elastio#6509).
Thus we need to downgrade kernels on these Fedora versions to fix CI.
It's also still useful to run CI tests on different kernel versions.

[CI/internal] Downgrade kernels on Fedora 35/36

---

src/elastio-snap.c

It was agreed in #39 that the COW file should be switched to an immutable one while the driver works to prevent it from moving or copying and thus guaranteeing the correct driver's behavior.

Implement immutable cow files

---

INSTALL.md
dist/elastio-snap.spec
src/elastio-snap.h

It's a milestone before API change #187 and then Linux kernel 6 support.

Bump new version 0.11.1

---

app/elioctl.c
dist/elastio-snap.spec
doc/elioctl.8
doc/elioctl.8.html
doc/elioctl.8.md
lib/libelastio-snap.c
lib/libelastio-snap.h
src/elastio-snap.c
src/elastio-snap.h
tests/elastio_snap.py
tests/test_multipart.py
tests/test_reload.py
tests/test_setup.py
tests/test_transition_incremental.py

Added an optional `-i` argument to `elioctl` to switch off IO errors
propagation on snapshot read when the snap is in the failed state.
The same arg has been added to the library functions to setup a snap and
transition to a snap.
As result, the entire error handling has been refactored a bit.
Got rid of `sd_memory_fail_code` and `sd_cow_fail_state` snapshot
struct members. The error managing with usage of three error states, two
mentioned plus `sd_fail_code` was superfluous. Moreover, in case of
the snap dev memory mapping, IO errors were not propagated just in case
of the 2 errors: mem is too low and COW file size exceeded. Now all
other possible errors should not kill userspace app with `SIGBUS` if it
reads the snap as a memory-mapped file.
Resolves #185

Implement functionality to switch on/of EIO propagation on snap read

---

dist/elastio-snap.spec
dist/system-shutdown/umount_rootfs.shutdown

Testsed on Ubuntu 20.04. When reboot OS, than snapshots did not reload due initramfs:
It was because it need to reapply journal and cannot do it in readonly mode. For avoid this we should remount rootfs to ro at the end of shutdown.
Fresh systems based on systemd and there is script, executed on shutdown.

Add sytemd shutdown script for consistence rootfs

---

INSTALL.md
dist/elastio-snap.spec
src/elastio-snap.c
src/elastio-snap.h

It's a milestone after API change #187 and addition of the Linux kernel 6 and Fedora 37 support #204, #209.

Bump new version 0.12.1

---

.github/workflows/ci.yml

Now `https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64` returns 404 for Fedora 35. It may happen for any Fedora version time to time. The solution is not to use `yum/dnf` and use `rpm` to install kernel packages on CI. `rpm` does not fetch updates from all repos during the package installation.

[Internal/CI] Fix CI on Fedora when mirrors are down

---

tests/test_snapshot.py

Previously, there were assumptions that immutable cow file functionality doesn't work correctly on all distributives. Hence, additional CI tests have been implemented to verify this.

Add tests for immutable cow file

---

src/elastio-snap.c

The issue is related to these error messages noticed on PopOS (v6.0.12):
```
[  693.318921] elastio-snap: ioctl command received: 1074020613
[  693.318927] elastio-snap: received transition inc ioctl - 7
[  693.318929] elastio-snap: allocating device struct
[  693.318931] elastio-snap: initializing tracer
[  693.318933] elastio-snap: creating kernel cow thread
[  693.319053] elastio-snap: getting the base block device's make_request_fn
[  693.319055] elastio-snap: original mrf is already replaced with the tracing_mrf = 000000000f1649ea
[  693.319057] elastio-snap: found already traced device dm-5 with the same original bd_ops. orig mrf = 0000000007ac3a93; orig ops = 000000005947874e; tracing ops = 00000000f799ecd7
[  693.319059] elastio-snap: using already existing tracing ops for device …
```

Fix issue with CoW file lock

---

tests/elastio_snap.py
tests/test_destroy.py
tests/test_reload.py

It was rarely seen on older kernels (f.e., Centos 7, v3.10) that sometimes the snapshot device cannot be instantaneously destroyed in the LVM configuration. It doesn't look like a serious driver issue with hidden consequences, so a simple retry functionality is suggested. Apart from that, the additional refactoring fixes were made for `test_reload.py` to make the tests more correct (removed unneded mount/umount cleanups).
Closes #202

Add retry logic on elastio_snap_destroy

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml

Closes #239
I'd say it closes only `x86_64` half of the task.
But then I thought we'll have Fedora 38 with the 6.1 kernel soon. And for that we will have boxes with both architectures for sure.

Add build for AL2023 x86_64

---

src/elastio-snap.c
tests/test_setup.py
tests/util.py

Currently, the size of the COW file is the sum of the header size, mapping section, and the snapshot data itself.
This was added on purpose in one of the previous tasks and caused some issues with other tests. This approach
implicitly adds some additional size to the `fallocate` specified by the user. It is now agreed that for the system
administrators, it is more critical to precisely control the used disk space used, so we will bring the initial behavior
back. This means, that if the user specifies 10% of the disk for the COW file, this should be the precise size of the
COW file and no additional data should be added to it.
Changes:
* Brought back the previous logic of the COW file size calculation
* Added two CI tests that compare the expected and real COW file sizes
Closes #253

Create cow file precisely according to the user setting

---

src/elastio-snap.c

Make sure the cow file size is the same in:
- /proc/elastio-snap-info
- elioctl info
- real cow file
Related to #253

Fix cow file size in /proc/elastio-snap-info

---

.github/buildbox/Vagrantfile
.github/workflows/ci.yml
src/configure-tests/feature-tests/bio_set_op_attrs.c
src/elastio-snap.c
tests/devicetestcase.py
tests/devicetestcase_multipart.py
tests/test_multipart.py
tests/test_snapshot.py
tests/util.py

* Enable Fedora 38
* Added compat for bio_set_op_attrs
* Fixed kernel panic on dereferencing the wrong address
* Increased volume sizes for the new mkfs.xfs (needs at least 300 MB per partition)
Closes #247

Fix for the Linux Kernel v6.2 (Fedora 37/38)

---

src/elastio-snap.c

Main changes:
* Returned back `real_fallocate` function (the one that actually makes allocation fast)
* Added "write ahead" before the direct write takes place on the module unload
Explanation on the last one:  this covers the case when the module is removed in the dormant state. In such a case, the direct write to the COW file takes place to write the rest of bio requests which have not been processed yet. However, it may (and likely will) happen that the COW file extents, which are being used for the direct write, aren't initialized by the FS. Hence, if we simply write there, there's no chance this data will be available at the next volume mount. To make this possible, we write some data ahead to ensure the extent is valid during the direct write operation.
Closes #260

Accelerate cow file allocation

---

.github/workflows/ci.yml
Makefile
dist/elastio-snap.spec
lib/libelastio-snap.h
src/elastio-snap.c
tests/test_update_image.py
utils/update-img.c

This PR introduces the working `update-img` utility and the working `test_update_sequence` check on Centos 8 + aarch64.
It was found that the update-img utility never actually worked on Centos 8 + aarch64. This was caused by the inconsistency of COW_BLOCK_SIZE in the driver and the utility itself because the last one didn't include the relevant kernel config (`kernel-config.h`).
Apart from that, the COW file overflow bug was found when `__cow_file_extents_zero_fill_ahead` was called from multiple places instead of just one (when the driver switches to the dormant state).
Both of these have been fixed in this PR.
Closes #266

Implement update-img for Centos8

---

.github/workflows/ci.yml
tests/test_snapshot.py

Long story short, it was proven to be not a bug but rather an incorrect test.
In some cases, we write to the sector already being tracked, which results in a
non-incrementing `nr_changed_blocks` counter. That happened because a small
amount of data was written (about 15 bytes) and the chances of writing to the
tracked sector were relatively high. The fix is to write more to increase the probability
of writing to the sector which isn't tracked.
Closes #167

Fix test_track_writes failure

---

Makefile
src/Makefile

If called `make -B` after `make clean`, the behavior of Makefile was a bit inaccurate as we didn't 
track the `kernel-config.h` dependency for the `driver` target. This caused the `driver` target to
create `kernel-config.h` underneath and also forced the root Makefile to regenerate it as a "fresh
one". Hence, the script was called twice, which took twice more time.
Closes #280

Fix Makefile to call genconfig.sh only once

---

src/nl_debug.c

Minor fix to get a timestamp on all supported kernels
Closes #279

Fix compilation of nl_debug.o for v3.x & v4.x kernels

---

src/configure-tests/feature-tests/bd_has_submit_bio.c
src/main.c

A new flag `bd_has_submit_bio` has been introduced in the new v6.4 Linux kernel. This flag defines if the `fops->submit_bio` or the other handler should be called. In this patch, we align the driver with this change by handling `bd_has_submit_bio` flag.
To do that, the `__tracer_transition_tracing` function has been rewritten to have access to the `tracing_params` struct through the `dev` pointer. Actually, this should have been done way earlier, because it was the question of time when we need the `dev` pointer (previously we passed `NULL` instead of the `dev` to end the tracing).
Apart from that, an additional compat has been added to check if the `bd_has_submit_bio` variable exists.
Closes #290

Implement support kernel v6.4

---

lib/libelastio-snap.c

The main concept is to create a reload script when the snapshot is created or changes its state, allowing the kernel to call it before the root file system is mounted. This functionality has been implemented in libelastio-snap as it's used in both elastio and elioctl.
Works everywhere but Fedora 38, Ubuntu 20.04 and Ubuntu 22.04. The relevant issue is here: #292,
Closes #289

Implement snapshot/incremental reload functionality

---

src/main.c

This patch introduces two fixes for Fedora and Ubuntu distributives to make the reload functionality work.
In general, this resolves the issues with false umounts. For Fedora, it was seen that the umount of the '.' directory took place during operation. There were no results in finding the exact instance that does it and why, but it doesn't look okay for regular operation. Hence, the code was corrected to accept only absolute paths instead of absolute + relative (as in this situation).
For Ubuntu the problem was different. Additional mount points were created for the root volume, which caused false umount handling in the driver. To fix that, we now check the vfsmount pointers to ensure we are dealing with the initial root volume.
Closes #292

Reload doesn't work on Ubuntu & Fedora

---

dist/initramfs/reload

Apparently, AWS has patched its base utils, which works differently when we try to use our scripts.
In this particular case, their `ls` utility doesn't support a [real basic] flag `-l`. This caused our reload
script to crash without reloading the subscripts for each particular volume that is tracked by the
driver.
Closes #297

Fix snapshot reload on ec2 instances
